# Index
## array 1D
## slicing(lát cắt)
phần lớn cách sử dụng tương tự như list


In [2]:
import numpy as np

In [3]:

array = np.array([2, 4, 6, 8, 10])
array[3]

8

In [5]:
array = np.array([2, 4, 6, 8, 10])
array[2:4]

array([6, 8])

# Tương tự có các thao tác cho 2D 
sudoku_game[3:6, 3:6] 

#array([[0, 0, 2],[0, 0, 7],[0, 8, 3]])
- sort
- Boolean masks (tương tự đối với 2D)

In [7]:
# Boolean masks
one_to_five = np.arange(1, 6)

one_to_five
mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False])

In [16]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
classroom_ids_and_sizes

classroom_ids_and_sizes[:, 0][classroom_ids_and_sizes[:, 1] % 2 == 0] # thao tác tìm kiếm

array([1, 4])

In [ ]:
# indices(chỉ số)
- Find and replace

In [15]:
sudoku_game = np.array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
[0, 0, 5, 0, 0, 9, 0, 0, 1],
[0, 7, 0, 0, 6, 0, 0, 4, 3],
[0, 0, 6, 0, 0, 2, 0, 8, 7],
[1, 9, 0, 0, 0, 7, 4, 0, 0],
[0, 5, 0, 0, 8, 3, 0, 0, 0],
[6, 0, 0, 0, 0, 0, 1, 0, 5],
[0, 0, 3, 5, 0, 8, 6, 9, 0],
[0, 4, 2, 9, 1, 0, 3, 0, 0]])
sudoku_game


row_ind, column_ind = np.where(sudoku_game == 0)

row_ind, column_ind

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8], dtype=int64))

In [17]:
np.where(sudoku_game == 0,"", sudoku_game) # find and replace

array([['', '', '4', '3', '', '', '2', '', '9'],
       ['', '', '5', '', '', '9', '', '', '1'],
       ['', '7', '', '', '6', '', '', '4', '3'],
       ['', '', '6', '', '', '2', '', '8', '7'],
       ['1', '9', '', '', '', '7', '4', '', ''],
       ['', '5', '', '', '8', '3', '', '', ''],
       ['6', '', '', '', '', '', '1', '', '5'],
       ['', '', '3', '5', '', '8', '6', '9', ''],
       ['', '4', '2', '9', '1', '', '3', '', '']], dtype='<U11')

# connect array
- np.concatenate((a, b))
- attention plus two matrix follow define matrix in Curriculum(giáo trình )

In [18]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])

new_classrooms = np.array([[5, 30], [5, 17]])

np.concatenate((classroom_ids_and_sizes, new_classrooms))

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 5, 17]])

# Connect colums 
- axis = 1: theo chiều ngang
- axis = 0: theo chiều dọc

In [29]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])

grade_levels_and_teachers = np.array([[1,"James"], [1,"George"], [3,"Amy"], [3,"Meehir"]])

classroom_data = np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)
classroom_data

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U11')

# np.delete(array, index, axis = 0 or 1)


In [30]:
np.delete(classroom_data, 1, axis = 1) # xóa cột 1

array([['1', '1', 'James'],
       ['2', '1', 'George'],
       ['3', '3', 'Amy'],
       ['4', '3', 'Meehir']], dtype='<U11')