In [3]:
import numpy as np

# create array 1D from list
vector = [1, 2, 3, 4, 5]
vt = np.array(vector)
vt
type(vt)

numpy.ndarray

In [4]:
# create arry 2D from list
vector1 = [[1, 3, 4], [2, 3, 4], [3, 4, 5]]
vt1 = np.array(vector1)
vt1

array([[1, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

# Array in numpy can contain many different data type
1. np.zeros((n, m)): create a array have size n rows, m columns contain values 0
2. np.random.random(n, m): array have size n, m the elements has value random from 0-1 (phân phối đều)
3. np.arange((-3,4)): array 1D contain interger continue from -3 -> 4
   np.arange(5): arr 1D contain interger continue 0 -> 5
   np.arange(-3, 4, 3): 4 is the step

In [6]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.random.random((2, 4))

array([[0.57998359, 0.58909011, 0.48947102, 0.57324207],
       [0.66058578, 0.56161082, 0.01931511, 0.53840827]])

In [8]:
np.arange(-3, 4)

array([-3, -2, -1,  0,  1,  2,  3])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(-3, 4, 3)

array([-3,  0,  3])

# Array 3D

In [22]:
array_1_2D = np.array([[1, 2], [5, 7]])

array_2_2D = np.array([[8, 9], [5, 7]])

array_3_2D = np.array([[1, 2], [5, 7]])

array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print(array_3D)
print("The size of array_3D is: ",array_3D.shape)

[[[1 2]
  [5 7]]

 [[8 9]
  [5 7]]

 [[1 2]
  [5 7]]]
The size of array_3D is:  (3, 2, 2)


# Vertor array, methods
- shape(): return size of array 
- flatten(): change arange two demesion as one denension
- reshape(2, 3): change hình dạng của mạng không làm thay đổi số lượng phần tử
- .dtype: confirm data type of a array
- .astype(np.int32): ép kiểu data type thành int, có thể float64

In [24]:
array = np.array([[1, 2], [5, 7], [6, 6]])
array.flatten()

array([1, 2, 5, 7, 6, 6])

In [25]:
array = np.array([[1, 2], [5, 7], [6, 6]])
array.reshape((2, 3))

array([[1, 2, 5],
       [7, 6, 6]])

In [26]:
array.reshape((3, 3))
# không thể thay đổi về ma trận 3 3 do lỗi kích thước

ValueError: cannot reshape array of size 6 into shape (3,3)

In [27]:
np.array([1.32, 5.78, 175.55]).dtype

dtype('float64')

In [ ]:
boolean_array = np.array([[True, False], [False, False]], dtype=np.bool_)
boolean_array.astype(np.int32)