# 1 số cấu lệnh numpy

In [18]:
import numpy as np
import random
print(np.__version__)

1.21.5


In [10]:
# create array 2D
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [12]:
# kiểm tra kích thước
print(arr.ndim)

2


In [14]:
# mảng chứa kiểu strings
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [15]:
# copy và thay đổi phần tử
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
# lặp xuyên qua mảng 3D
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [19]:
# lấy ngẫu nhiên
x = random.choice([3, 5, 7, 9])

print(x)

9


In [20]:
# randon thứ tự các phần tử trong mảng
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 5 1 4 3]
